// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfObcLCSZJ7m-fheaisGoisX6eRF_rpq8',
    appId: '1:586687663283:web:0becb52c119f752f5d34c6',
    messagingSenderId: '586687663283',
    projectId: 'reddit-fk',
    authDomain: 'reddit-fk.firebaseapp.com',
    storageBucket: 'reddit-fk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGzR3GvE1aIXm_KhIsBqKyIGE42JKDH_Q',
    appId: '1:586687663283:android:de998e86fec222735d34c6',
    messagingSenderId: '586687663283',
    projectId: 'reddit-fk',
    storageBucket: 'reddit-fk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpwyfd-rQkx2B8iwjckd5doG2MRu1RYGg',
    appId: '1:586687663283:ios:b51d051a0282f7b35d34c6',
    messagingSenderId: '586687663283',
    projectId: 'reddit-fk',
    storageBucket: 'reddit-fk.appspot.com',
    iosBundleId: 'com.example.blogBud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpwyfd-rQkx2B8iwjckd5doG2MRu1RYGg',
    appId: '1:586687663283:ios:4092f84847ed9a215d34c6',
    messagingSenderId: '586687663283',
    projectId: 'reddit-fk',
    storageBucket: 'reddit-fk.appspot.com',
    iosBundleId: 'com.example.blogBud.RunnerTests',
  );
}
